language: java
jdk: oraclejdk8

script:
 - mv variables.conf.tmpl variables.conf
 - ./configure.sh
 - ./install-all.sh
 - ./copy-config.sh
 - cp ~/opt/regal/conf/application.conf ~/opt/regal/regal-api/conf
 - sudo cp ~/opt/regal/conf/elasticsearch.yml /etc/elasticsearch
 - ./restart-all.sh
 - ./run-integration-tests.sh

